### ISSUE TITLE
100% on closing terminal tab

### ISSUE THREAD

**Issue by Maxim-Filimonov** [Floobits/flootty#34]
Hi,
I've noticed when i'm connected to my colleagues terminal there is no easy way to exit it without exiting his flootty session. I usually just close a Tab in iTerm but since 3.1.2 it leads to 100% cpu usage of python process EVERY time. I have updated to 3.1.3 still the same issue present.
CPU sample - https://gist.github.com/Maxim-Filimonov/bb49615b549615ade331

**Comment by ggreer** [comment]
Thanks for the CPU sample. Just to make sure: You closing your terminal tab causes Python to use 100% of CPU on your system, not your friend's right?

**Comment by Maxim-Filimonov** [comment]
Yes on my system

**Comment by ggreer** [comment]
Annoyingly, I can't seem to reproduce this issue locally. I've tried different versions of Python and flootty. I've also tried both Terminal.app and iTerm. Like you, I'm on OS X 10.10.3.

Are there any other clues you can give me? I have some ideas on where the infinite loop might be, but it's really hard to pin down without a locally reproducible case.

**Comment by Maxim-Filimonov** [comment]
I reinstalled my OS and it works now , so i cannot reproduce it either :( Closing this for now

**Comment by ggreer** [comment]
I'm glad it works for you now. I guess we'll never know the cause, but hopefully it wasn't my fault. :)
