### ISSUE TITLE
Unable to exit flootty

### ISSUE THREAD

**Issue by danielcompton** [Floobits/flootty#37]
Once someone closes their host terminal, my session doesn't work and I can't exit it. I get:

```
Error from server: Terminal 4 doesn't exist
Error from server: Terminal 4 doesn't exist
...
```

I'm using OS X with flootty 3.1.6

**Comment by ggreer** [comment]
Thanks for the bug report. Can you please give me the exact version of OS X and python that you're using? `which python` and `python -V` should be enough info.

**Comment by ggreer** [comment]
Nevermind, I found the bug. Update to 3.1.7 (`pip install --upgrade flootty`) and you should be good.
